import { Product, Category } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Floral', imageId: 'category-floral' },
  { id: '2', name: 'Amadeirado', imageId: 'category-woody' },
  { id: '3', name: 'Cítrico', imageId: 'category-citrus' },
  { id: '4', name: 'Oriental', imageId: 'category-oriental' },
  { id: '5', name: 'Decantes', imageId: 'category-decants' },
  { id: '6', name: 'Best Sellers', imageId: 'best-sellers' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Coco Mademoiselle',
    brand: 'Chanel',
    price: 989.0,
    oldPrice: 1100.0,
    imageId: 'product-1',
    type: 'sealed',
    status: 'in-stock',
    stock: 45,
    category: 'Frasco',
  },
  {
    id: '2',
    name: 'Sauvage Elixir',
    brand: 'Dior',
    price: 89.9,
    imageId: 'product-2',
    type: 'decant',
    decantMl: 5,
    status: 'low-stock',
    stock: 5,
    category: 'Decante 5ml',
  },
  {
    id: '3',
    name: 'Black Orchid',
    brand: 'Tom Ford',
    price: 1290.0,
    oldPrice: 1450.0,
    imageId: 'product-3',
    type: 'sealed',
    status: 'out-of-stock',
    stock: 0,
    category: 'Frasco',
  },
  {
    id: '4',
    name: 'Libre Eau de Parfum',
    brand: 'YSL',
    price: 129.9,
    imageId: 'product-4',
    type: 'decant',
    decantMl: 10,
    status: 'in-stock',
    stock: 20,
    category: 'Decante 10ml',
  },
  {
    id: '5',
    name: 'Chanel No. 5',
    brand: 'Chanel',
    price: 850.0,
    imageId: 'table-1',
    type: 'sealed',
    status: 'in-stock',
    stock: 45,
    category: 'Frasco',
  },
  {
    id: '6',
    name: 'Acqua Di Gio',
    brand: 'Giorgio Armani',
    price: 420.0,
    imageId: 'recent-2',
    type: 'sealed',
    status: 'in-stock',
    stock: 30,
    category: 'Frasco',
  },
  {
    id: '7',
    name: 'La Vie Est Belle',
    brand: 'Lancôme',
    price: 620.0,
    imageId: 'recent-3',
    type: 'sealed',
    status: 'low-stock',
    stock: 8,
    category: 'Frasco',
  },
];
